version: "3.9"
services:
  redis:
    container_name: redismod_market_info
    image: "redislabs/redismod:edge"
    ports:
      - 6379:6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure